### PR TITLE
Promote recommended settings as default

### PR DESCRIPTION
**Pull request by Mygod**
P.S. Could you set default branch to shadowsocks for this repo?

### CODE REVIEW

**Comment by Mygod** [comment]
Okay this PR might look cool at **first** glance, but on **second** thought I realized this could as well break upgrades and bring compatibility issues. Maybe it's better to revert this?

**Comment by madeye** [comment]
I think it's good to change the default settings for Android. I will be careful next time when merging the upstream.

**Comment by Mygod** [comment]
I mean people already started using KCP on Android. They might upgrade to this new version, find out that KCP stops working and regard this as a bug.

**Comment by madeye** [comment]
OK, it sounds a problem. Let me revert the change.

**Pull request merged**
